---
- name: Ensure VirtualBox is present
  become: yes
  package:
    name: "{{ vb_package[ansible_os_family] }}"
    state: present
  vars:
    vb_package:
      Debian: virtualbox
      RedHat: VirtualBox