---
- name: Ensure oh-my-zsh dependencies are installed
  become: yes
  package:
    name: "{{ item }}"
    state: present
  loop:
    - zsh
    - curl
  tags: ['oh-my-zsh']

- name: Install oh-my-zsh
  shell:
    cmd: ZSH= sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  tags: ['oh-my-zsh']

- name: Find which zsh to use
  shell:
    cmd: which zsh
  register: which_zsh
  tags: ['oh-my-zsh']

- name: Find current user
  shell:
    cmd: echo $USER
  register: current_username
  tags: ['oh-my-zsh']

- name: Set zsh as default shell for user
  become: yes
  user:
    name: "{{ current_username.stdout }}"
    shell: "{{ which_zsh.stdout }}"
    state: present
  tags: ['oh-my-zsh']