---
- hosts: all
  gather_facts: yes

  vars_files:
    - vars/default.config.yml

  pre_tasks:
    - name: Include playbook configuration
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

    - name: Run distro specific pre-tasks
      include_tasks:
        file: "tasks/setup_pre_tasks/{{ ansible_distribution }}.yml"
        apply:
          tags: ['always']
      tags: ['always']

  tasks:
    - name: Install packages
      block:
        - import_tasks: tasks/flatpak.yml
          tags: ['flatpak']
        - import_tasks: tasks/packages.yml
      tags: ['packages']

    - name: Set zsh as default shell for user
      become: yes
      user:
        name: "{{ ansible_user_id }}"
        shell: "/usr/bin/zsh"
        state: present
      tags: ['terminal']

    - name: Init dotfiles
      import_tasks: tasks/init_dotfiles.yml
      tags: ['dotfiles']

    - name: Configure Gnome DE
      import_tasks: tasks/gnome.yml
      tags: ['gnome', 'de']
