---
- hosts: all
  gather_facts: yes

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

    - name: Run distro specific pre-tasks.
      include_tasks: "tasks/setup_pre_tasks/{{ ansible_distribution }}.yml"
      tags: ['always']

  roles:
    - role: geerlingguy.ruby
      become: yes
    - role: geerlingguy.go
      become: yes
    - role: gantsign.minikube
      become: yes
    - role: geerlingguy.ansible
      become: yes
    - role: geerlingguy.docker
      become: yes
      vars:
        docker_users:
          - "{{ ansible_user_id }}"
    - role: andrewrothstein.terraform
    - role: darkwizard242.onepassword

  tasks:
    - name: Install packages.
      become: yes
      block:
        - import_tasks: tasks/install/flatpak.yml
        - import_tasks: tasks/install/snap.yml
        - import_tasks: tasks/install/packages.yml
      when: install_packages
      tags: ['packages']

    - import_tasks: tasks/configure/terminal.yml
      become: yes
      when: configure_terminal
      tags: ['terminal']

    - import_tasks: tasks/configure/dotfiles.yml
      when: configure_dotfiles
      tags: ['dotfiles']
