---
- hosts: all
  
  vars_files:
    - "vars/default.config.yml"

  pre_tasks:
    - name: Include playbook configuration
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/vars/{{ ansible_os_family }}.config.yml"
        - "{{ playbook_dir }}/vars/{{ ansible_distribution }}.config.yml"
      tags: ['always']

    - name: Infer control variables
      include_vars: vars/_inferred.yml
      tags: ['always']
    
    - name: Check if distro specific pre-tasks exist
      local_action: 
        module: stat 
        path: "tasks/distro_pre_tasks/{{ ansible_distribution }}.yml"
      register: pre_tasks_file
      tags: ['always']

    - name: Run distro specific pre-tasks
      include_tasks: "tasks/distro_pre_tasks/{{ ansible_distribution }}.yml"
      when: pre_tasks_file.stat.exists
      tags: ['always']
  
  tasks:
    - name: Install specified packages
      include_tasks: tasks/install_packages/main.yml

    - name: Configure terminal
      import_tasks: tasks/configure_terminal/main.yml
      tags: ['terminal']