---
- hosts: all
  gather_facts: yes
  
  vars_files:
    - vars/default.config.yml

  pre_tasks:
    - name: test
      debug:
        var: ansible_env.XDG_CURRENT_DESKTOP

    - name: test
      debug:
        var: ansible_facts

    - meta: end_play

    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']
    
    - name: Run distro specific pre-tasks
      include_tasks: "{{ lookup('first_found', params) }}"
      vars:
        params:
          files:
            - "{{ ansible_distribution }}.yml"
            - "{{ ansible_os_family }}.yml"
            - default.yml
          paths:
            - tasks/setup_pre_tasks
      tags: [always]
  
  roles:
    - role: general/basic_term_tools
      tags: [ always, common ]

    - role: package_manager/flatpak
      tags: [ always, common, software, package_manager ]
    
    - role: package_manager/snaps
      tags: [ always, common, software, package_manager ]
    
    - role: software/firefox
      tags: [ always, common, software, browser ]

    - role: software/1password
      tags: [ always, password_management, software ]

    - role: configuration/dotfiles
      tags: [ dev, configuration ]

    - role: configuration/terminal
      tags: [ dev, configuration ]

    - role: lang/python
      tags: [ dev, lang ]

    - role: lang/java
      tags: [ dev, lang ]

    - role: lang/ruby
      tags: [ dev, lang ]

    - role: lang/go
      tags: [ dev, lang ]

    - role: lang/cpp
      tags: [ dev, lang ]

    - role: software/git
      tags: [ dev, software ]

    - role: software/vscode
      tags: [ dev, software ]

    - role: software/ansible
      tags: [ dev, software ]

    - role: software/jekyll
      tags: [ dev, software ]

    - role: software/vagrant
      tags: [ dev, software ]

    - role: software/virtualbox
      tags: [ dev, software ]

    - role: software/dbeaver
      tags: [ dev, software ]

    - role: software/chromium
      tags: [ dev, software ]

    - role: software/freecad
      tags: [ 3dprint, software ]

    - role: software/prusa_slicer
      tags: [ 3dprint, software ]

    - role: software/steam
      tags: [ gaming, software ]

    - role: software/spotify
      tags: [ gaming, dev, software ]

    - role: software/discord
      tags: [ gaming, software ]

    #- role: configuration/gnome
    #  when: ([ansible_env.XDG_CURRENT_DESKTOP | default(''), ansible_env.ORIGINAL_XDG_CURRENT_DESKTOP | default(''), desktop_env | default('')] | join('') | regex_search('gnome', ignorecase=True)) != ''
    #  tags: [ never, desktop_env, gnome, configuration ]