---
- hosts: all
  
  vars_files:
    - vars/default.config.yml
    - "vars/{{ ansible_os_family }}.yml"

  pre_tasks:
    - name: Include playbook configuration
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/vars/config.yml"
    
    - name: Update apt cache
      become: true
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'
  
  tasks:
    - import_tasks: tasks/install_packages/main.yml
      tags: ['software']

    - import_tasks: tasks/configure_terminal/main.yml
      when: configure_terminal
      tags: ['terminal']
