---
- hosts: all
  gather_facts: yes

  vars_files:
    - vars/default.config.yml

  pre_tasks:
    - name: Include playbook configuration
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"

    - name: Run distro specific pre-tasks
      include_tasks: "tasks/setup_pre_tasks/{{ ansible_distribution | lower }}.yml"

  tasks:
    - name: Ensure common terminal tools are present
      become: yes
      package:
        name: "{{ common_term_tools }}"
        state: present

    - name: Install package managers
      import_tasks: tasks/package_manager/main.yml

    - name: Install general use software (browsers, office, etc)
      import_tasks: tasks/gen/main.yml

    - name: Install programming languages
      import_tasks: tasks/lang/main.yml

    - name: Install dev tools
      import_tasks: tasks/dev_tools/main.yml
