---
- hosts: all
  
  vars_files:
    - "vars/default.config.yml"

  pre_tasks:
    - name: Run distro specific pre-tasks
      include_tasks: "{{ lookup('first_found', params) }}"
      vars:
        params:
          files:
            - "{{ ansible_distribution }}.yml"
            - "{{ ansible_os_family }}.yml"
            - default.yml
          paths:
            - tasks/setup_pre_tasks
      tags: [always]
  
  tasks:
    - name: Include common roles
      include_role: 
        name: "{{ role }}"
      loop:
        - general/basic_term_tools
        - package_manager/flatpak
        - package_manager/snaps
        - software/firefox
      loop_control:
        loop_var: role
      tags: [always, common]

    - name: Include password manager
      include_role:
        name: software/1password
      tags: [always, password_management]

    #- name: Include dev roles
    #  incldue_role:
    #    name: "{{ role }}"
    #  loop:
    #    - configuration/dotfiles
    #    - configuration/terminal
    #    - lang/python
    #    - lang/java
    #    - lang/ruby
    #    - lang/go
    #    - lang/cpp
    #    - software/git
    #    - software/vscode
    #    - software/ansible
    #    - software/jekyll
    #    - software/vagrant
    #    - software/virtualbox
    #    - software/dbeaver
    #    - software/chromium
    #  loop_control:
    #    loop_var: role
    #  tags: [always, dev]

    - name: Include 3dprint roles
      include_role:
        name: "{{ role }}"
      loop:
        - software/freecad
        - software/prusa_slicer
      loop_control:
        loop_var: role
      tags: [always, 3dprint]

    - name: Include gaming roles
      include_role:
        name: "{{ role }}"
      loop:
        - software/steam
        - software/spotify
        - software/discord
      loop_control:
        loop_var: role
      tags: [always, gaming]