---
- name: Ensure flatpak package is present
  become: yes
  package:
    name: flatpak
    state: present

- name: Check Flathub configuration
  lineinfile:
    name: /var/lib/flatpak/repo/config
    line: "xa.title=Fedora Flathub Selection"
    state: absent
  check_mode: yes
  register: flatpak_conf

- name: Remove Fedora filtered Flathub remote
  become: yes
  flatpak_remote:
    name: flathub
    state: absent
  when: flatpak_conf.changed

- name: Ensure Flathub remote is present
  become: yes
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    state: present
