---
- name: Ensure flatpak package is present
  become: yes
  package:
    name: flatpak
    state: present

- name: Ensure flathub repositories are unfiltered
  become: yes
  ini_file:
    path: /var/lib/flatpak/repo/config
    section: 'remote "flathub"'
    option: xa.filtered
    state: absent
    backup: yes

- name: Ensure flathub repositories are enabled
  become: yes
  ini_file:
    path: /var/lib/flatpak/repo/config
    section: 'remote "flathub"'
    option: xa.disabled
    value: 'false'
    state: present
    backup: yes
