---
- name: Ensure flatpak package is present
  become: yes
  package:
    name: flatpak
    state: present

- name: Ensure flathub repositories are included
  become: yes
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    state: present

- name: Ensure flathub repositories are unfiltered
  become: yes
  lineinfile:
    path: /var/lib/flatpak/repo/config
    state: absent
    insertafter: '[remote "flathub"]'
    regexp: '^xa.filter=.*flathub'
