---
- name: Ensure flatpak package is present
  become: yes
  package:
    name: flatpak
    state: present

- name: Check flathub remote filter
  lineinfile:
    name: /var/lib/flatpak/repo/config
    regexp: "^xa.filter=.*flathub.filter"
    state: absent
  check_mode: yes
  register: flatpak_conf

- name: Remove filtered flathub remote
  become: yes
  command: flatpak remote-delete flathub
  when: flatpak_conf.changed

- name: Ensure Flathub remote is present
  become: yes
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    state: present
