---
- name: Run chezmoi init
  shell:
    cmd: |
      chezmoi init \
      --apply https://{{ dotfiles.host }}/{{ dotfiles.repo }}.git \
      --promptString 'What is your email address'={{ email }}
    creates: $HOME/.local/share/chezmoi/

- name: Change git remote to SSH
  git_config:
    repo: $HOME/.local/share/chezmoi/
    scope: local
    name: remote.origin.url
    value: git@{{ dotfiles.host }}:{{ dotfiles.repo }}.git
