---
- name: Ensure state of system package repositories
  become: yes
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    enabled: "{{ item.enabled }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
  loop: "{{ system_package_repos }}"

- name: Ensure state of local system packages
  become: yes
  dnf:
    name: "{{ system_packages_local }}"
    state: present
    disable_gpg_check: yes
  tags: ['system']

- name: Ensure state of system packages
  become: yes
  dnf:
    name: "{{ system_packages[item] }}"
    state: "{{ item }}"
  loop: "{{ system_packages.keys() }}"
  tags: ['system']

- name: Ensure state of Flatpak packages
  become: yes
  community.general.flatpak:
    name: "{{ flatpak_packages[item] }}"
    state: "{{ item }}"
  loop: "{{ flatpak_packages.keys() }}"
  tags: ['flatpak']

- name: Ensure state of Pip packages
  pip:
    name: "{{ pip_packages[item] }}"
    state: "{{ item }}"
  loop: "{{ pip_packages.keys() }}"
  tags: ['pip']
