---
control:
  update_packages: yes
  profiles_list:
  - gaming
  free_plus_nonfree_repos: yes

profiles:
  common:    
    package_manager_list:
    - zsh
    - vim
    - wget
    - curl
    - tar
    - rsync
    - rclone
    
    flatpak_repos_list:
    - { name: flathub, url: "https://flathub.org/repo/flathub.flatpakrepo" }

    flatpak_packages_list:
    - com.spotify.Client
    - com.discordapp.Discord

  dev:
    package_manager_list:
    - git
    - vagrant
    - [python3, python3-pip]
    - ansible-lint
    - { Debian: openjdk-11-jdk, RedHat: java-11-openjdk }
    - { Debian: virtualbox, RedHat: VirtualBox }
    - { Debian:  [ruby-full, build-essential, zlib1g-dev], Fedora: [ruby, ruby-devel, openssl-devel, redhat-rpm-config, "@development-tools"] }

    flatpak_packages_list:
    - io.dbeaver.DBeaverCommunity
    - org.raspberrypi.rpi-imager
    - com.slack.Slack
    - org.freecadweb.FreeCAD
    - com.prusa3d.PrusaSlicer

    pip_packages_list:
    - virtualenv
    - ansible
  
  gaming:
    package_manager_list:
    - steam