---
dotfiles_repo: https://github.com/benchoncy/dotfiles.git
dotfiles_repo_version: master

nerdfonts_version: v2.1.0
powerlevel10k_version: v1.16.1

common_term_tools:
  - vim
  - wget
  - curl
  - tar
  - unzip
  - rsync
  - rclone
  - git

python_pip_packages:
  - pylint
  - pylama
  - virtualenv
  - pytest
