---
dotfiles_repo: github.com/benchoncy/dotfiles.git

system_package_repos:
  - name: visual-studio-code
    description: Microsoft offical VScode repository
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: yes
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

system_packages:
  present:
    - vim
    - wget
    - curl
    - tar
    - unzip
    - rsync
    - rclone
    - git
    - zsh
    - '@Development Tools'
    - python3
    - python3-pip
    - golang
    - java-latest-openjdk
    - vagrant
    - hugo
    - podman
    - code
  absent:
    - firefox

flatpak_packages:
  present:
    - com.google.Chrome
    - md.obsidian.Obsidian
    - com.slack.Slack
    - com.discordapp.Discord
    - org.videolan.VLC
    - org.freecadweb.FreeCAD
    - com.ultimaker.cura

brew_formulas:
  present:
    - chezmoi
    - pyenv
    - minikube
    - kubectl
    - terraform
    - packer
    - awscli

pip_packages:
  present:
    - pipenv
    - ansible
    - ansible-core
    - ansible-lint
    - molecule
    - molecule[docker]
    - molecule-vagrant

gnome:
  theme: "'Adwaita-dark'"
  color_scheme: "'prefer-dark'"
  background: "'file:///usr/share/backgrounds/fedora-workstation/calm.jpg'"
  background_dark: "'file:///usr/share/backgrounds/fedora-workstation/calm_dark.jpg'"
  favorite_apps:
    - com.google.Chrome.desktop
    - org.gnome.Terminal.desktop
    - org.gnome.Nautilus.desktop
    - code.desktop
    - md.obsidian.Obsidian.desktop
