---
dotfiles_repo: github.com/benchoncy/dotfiles.git

system_package_repos:
  - name: visual-studio-code
    description: Microsoft VScode
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: yes
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

  - name: hashicorp
    description: Hashicorp Stable
    baseurl: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
    enabled: yes
    gpgcheck: yes
    gpgkey: https://rpm.releases.hashicorp.com/gpg

  - name: google-chrome
    description: Google Chrome
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
    enabled: yes
    gpgcheck: yes
    gpgkey: https://dl.google.com/linux/linux_signing_key.pub

system_packages:
  present:
    - vim
    - wget
    - curl
    - tar
    - unzip
    - rsync
    - rclone
    - git
    - zsh
    - '@Development Tools'
    - python3
    - python3-pip
    - golang
    - java-latest-openjdk
    - vagrant
    - terraform
    - packer
    - hugo
    - podman
    - code
    - google-chrome-stable
  absent:
    - firefox

flatpak_packages:
  present:
    - md.obsidian.Obsidian
    - com.slack.Slack
    - com.discordapp.Discord
    - org.videolan.VLC
    - org.freecadweb.FreeCAD
    - com.ultimaker.cura

brew_formulas:
  present:
    - chezmoi
    - pyenv
    - minikube
    - kubectl
    - awscli

pip_packages:
  present:
    - pipenv
    - ansible
    - ansible-core
    - ansible-lint
    - molecule
    - molecule[docker]
    - molecule-vagrant

gnome:
  theme: "'Adwaita-dark'"
  color_scheme: "'prefer-dark'"
  background: "'file:///usr/share/backgrounds/fedora-workstation/calm.jpg'"
  background_dark: "'file:///usr/share/backgrounds/fedora-workstation/calm.jpg'"
  favorite_apps:
    - com.google.Chrome.desktop
    - org.gnome.Terminal.desktop
    - org.gnome.Nautilus.desktop
    - code.desktop
    - md.obsidian.Obsidian.desktop
