---
install_packages: yes
install_flatpaks: yes
install_snaps: yes
install_pips: yes
install_npms: no
configure_terminal: yes

package_manager_list:
  - git
  - zsh
  - vim
  - wget
  - curl
  - virtualbox
  - vagrant
  - tar
  - rsync
  - rclone
  - python3
  - python3-pip
  - ansible

distro_spec_package_manager_list: []

flatpak_default_repo: flathub
flatpak_repos_list:
  - { name: flathub, url: "https://flathub.org/repo/flathub.flatpakrepo" }

flatpak_packages_list:
  - io.dbeaver.DBeaverCommunity
  - org.raspberrypi.rpi-imager
  - org.zaproxy.ZAP
  - com.anydesk.Anydesk
  - com.spotify.Client
  - com.discordapp.Discord
  - com.slack.Slack
  - org.freecadweb.FreeCAD

snap_packages_list:
  - { name: notable, classic: yes }
  - { name: code, classic: yes }
  - cura-slicer

pip_packages_list:
  - virtualenv

npm_packages_list: []