---
email: ben@benstuart.ie

dotfiles:
  repo: benchoncy/dotfiles
  host: github.com

enable_free_rpm_fusion: yes
enable_nonfree_rpm_fusion: no

system_package_repos:
  - name: 1password
    description: 1Password Stable Channel
    baseurl: https://downloads.1password.com/linux/rpm/stable/$basearch
    enabled: yes
    gpgcheck: yes
    gpgkey: https://downloads.1password.com/linux/keys/1password.asc

  - name: code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: yes
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

  - name: hashicorp
    description: Hashicorp Stable
    baseurl: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
    enabled: yes
    gpgcheck: yes
    gpgkey: https://rpm.releases.hashicorp.com/gpg

  - name: kubernetes
    description: Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
    enabled: yes
    gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  
  - name: google-chrome
    description: Google Chrome
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/$basearch
    enabled: yes
    gpgcheck: yes
    gpgkey: https://dl-ssl.google.com/linux/linux_signing_key.pub

system_packages_local:
  - "https://github.com/twpayne/chezmoi/releases/download/v2.29.1/chezmoi-2.29.1-x86_64.rpm"  # Chezmoi
  - "https://storage.googleapis.com/minikube/releases/latest/minikube-latest.x86_64.rpm"  # Minikube

system_packages:
  present:
    # Password manager
    - 1password
    - 1password-cli
    # General cli tools
    - vim
    - wget
    - curl
    - tar
    - unzip
    - rsync
    - rclone
    - git
    - zsh
    # Browsers
    - firefox
    - google-chrome-stable
    # Dev tools
    - '@Development Tools'
    - python3
    - python3-pip
    - golang
    - java-latest-openjdk
    - vagrant
    - terraform
    - hugo
    - podman
    - code
    - awscli
    - kubectl

flatpak_packages:
  present:
    - md.obsidian.Obsidian
    - org.zotero.Zotero
    - org.videolan.VLC
    # 3d printing
    - org.freecadweb.FreeCAD
    - com.ultimaker.cura

pip_packages:
  present:
    - ansible
    - ansible-core
    - ansible-lint
    - molecule
    - molecule-containers
    - molecule-podman
    - molecule-vagrant
    - poetry

gnome:
  theme: "'Adwaita-dark'"
  color_scheme: "'prefer-dark'"
  background: "'file:///usr/share/backgrounds/fedora-workstation/calm.jpg'"
  background_dark: "'file:///usr/share/backgrounds/fedora-workstation/calm.jpg'"
  avatar:
    src: https://avatars.githubusercontent.com/u/25982949
  favorite_apps:
    - google-chrome.desktop
    - org.gnome.Terminal.desktop
    - org.gnome.Nautilus.desktop
    - code.desktop
    - md.obsidian.Obsidian.desktop
    - org.zotero.Zotero.desktop
    - 1password.desktop
