---
- name: Set dock layout in Gnome
  dconf:
    key: /org/gnome/shell/favorite-apps
    value: "{{ gnome.favorite_apps }}"
    state: present

- name: Set window theme in Gnome
  dconf:
    key: /org/gnome/desktop/interface/gtk-theme
    value: "{{ gnome.theme }}"
    state: present

- name: Set window theme in Gnome
  dconf:
    key: /org/gnome/desktop/background/picture-uri
    value: "{{ gnome.background }}"
    state: present
