---
dependency:
  name: galaxy
driver:
  name: containers
platforms:
  - name: instance
    image: "fedora:36"
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
