---
- name: Ensure flatpak package is present
  become: yes
  package:
    name: flatpak
    state: present

- name: Ensure flathub repositories are included
  become: yes
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    state: present