---
- name: Ensure flatpak package installed
  package:
    name: flatpak
    state: present
  when: ((flatpak_repos_list != None) and (flatpak_repos_list|length != 0))
    and ((flatpak_packages_list != None) and (flatpak_packages_list|length != 0))

- name: Ensure remote repositories are included
  community.general.flatpak_remote:
    name: "{{ item.name }}"
    flatpakrepo_url: "{{ item.url }}"
    state: present
  loop: "{{ flatpak_repos_list }}"
  when: (flatpak_repos_list != None) and (flatpak_repos_list|length != 0)

- name: Install via flatpak
  community.general.flatpak:
    name: "{{ item.name|default(item) }}"
    remote: "{{ item.repo|default(flatpak_default_repo) }}"
    state: present
  loop: "{{ flatpak_packages_list }}"
  when: (flatpak_packages_list != None) and (flatpak_packages_list|length != 0)
