---
- name: Ensure flatpak package are installed
  package:
    name: flatpak
    state: present

- name: Ensure remote repositories are included
  community.general.flatpak_remote:
    name: "{{ item.name }}"
    flatpakrepo_url: "{{ item.url }}"
    state: present
  loop: "{{ combined_profile.flatpak_repos_list }}"
  when: add_flatpak_repos

- name: Install via flatpak
  community.general.flatpak:
    name: "{{ item.name | default(item) }}"
    remote: "{{ item.repo | default(omit) }}"
    state: present
  loop: "{{ combined_profile.flatpak_packages_list }}"
  when: add_flatpaks
