---
- import_tasks: tasks/install_packages/packagem_install.yml
  become: true
  when: install_packages
  tags: ['package']

- import_tasks: tasks/install_packages/flatpak_install.yml
  become: true
  when: install_flatpaks
  tags: ['flatpak']

- import_tasks: tasks/install_packages/snap_install.yml
  become: true
  when: install_snaps
  tags: ['snap']
- import_tasks: tasks/install_packages/pip_install.yml
  when: install_pips
  tags: ['pip']

- import_tasks: tasks/install_packages/npm_install.yml
  when: install_npms
  tags: ['npm']