---
- name: Ensure nodejs & npm packages are installed
  package:
    name: "{{ item[ansible_distribution] | default(item[ansible_os_family]) | default(item['default']) | default(item) }}"
    state: present
  loop:
    - nodejs
    - npm

- name: Install via npm
  npm:
    name: "{{ item }}"
    global: yes
    state: present
  loop: "{{ combined_profile.npm_packages_list }}"