---
- name: Ensure python & pip packages are installed
  package:
    name: "{{ item[ansible_distribution] | default(item[ansible_os_family]) | default(item['default']) | default(item) }}"
    state: present
  loop:
  - python3
  - python3-pip

- name: Install via pip
  pip:
    name: "{{ item }}"
    state: present
  loop: "{{ combined_profile.pip_packages_list }}"