---
- name: Ensure snapd package installed
  package:
    name: snapd
    state: present
  when: ((snap_packages_list != None) and (snap_packages_list|length != 0))

- name: Install via snap
  community.general.snap:
    name: "{{ item.name|default(item) }}"
    channel: "{{ item.channel|default(omit) }}"
    classic: "{{ item.classic|default(omit) }}"
    state: present
  loop: "{{ snap_packages_list }}"
  when: ((snap_packages_list != None) and (snap_packages_list|length != 0))
