---
- name: Ensure snapd package is installed
  package:
    name: snapd
    state: present

- name: Install via snap
  community.general.snap:
    name: "{{ item.name|default(item) }}"
    channel: "{{ item.channel|default(omit) }}"
    classic: "{{ item.classic|default(omit) }}"
    state: present
  loop: "{{ combined_profile.snap_packages_list }}"
