---
- name: Ensure nerd-fonts/powerlevel10k dependencies are installed
  package:
    name:
      - git
    state: present
  tags: ['oh-my-zsh', 'powerlevel10k', 'nerd-fonts']

- name: Clone Nerd-fonts repository
  git:
    repo: https://github.com/ryanoasis/nerd-fonts.git
    dest: /tmp/nerd-fonts
    depth: 1
    version: "{{ nerdfonts_version }}"
  changed_when: false
  tags: ['oh-my-zsh', 'powerlevel10k', 'nerd-fonts']

- name: Install Nerd-fonts
  command:
    cmd: /tmp/nerd-fonts/install.sh
  args:
    creates:
      "{{ ansible_env.HOME }}/.local/share/fonts/NerdFonts"
  tags: ['oh-my-zsh', 'powerlevel10k', 'nerd-fonts']

- name: Clone powerlevel10k theme
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/powerlevel10k"
    depth: 1
    version: "{{ powerlevel10k_version }}"
