---
- name: Add 1password rpm key
  become: yes
  rpm_key:
    key: https://downloads.1password.com/linux/keys/1password.asc
    state: present

- name: Add 1passpord repo
  become: yes
  yum_repository:
    name: 1password
    description: 1Password Stable Channel
    baseurl: https://downloads.1password.com/linux/rpm/stable/$basearch
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://downloads.1password.com/linux/keys/1password.asc
    state: present
