---
- name: Edit dnf config to increase download speed.
  become: yes
  lineinfile:
    path: /etc/dnf/dnf.conf
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
  loop:
    - key: "max_parallel_downloads"
      value: "10"
    - key: "fastestmirror"
      value: "True"

- name: Enable rpmfussion repositories.
  become: yes
  dnf:
    name: "{{ item }}"
    disable_gpg_check: yes
  loop:
    - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
    - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm
