---
- name: Edit dnf config to increase download speed
  become: yes
  lineinfile:
    path: /etc/dnf/dnf.conf
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
  loop:
    - key: "max_parallel_downloads"
      value: "10"
    - key: "fastestmirror"
      value: "True"
