---
- name: Set dnf config
  become: yes
  lineinfile:
    path: /etc/dnf/dnf.conf
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
  loop:
    - key: "max_parallel_downloads"
      value: "10"

- name: Enable the Free RPM Fusion repository
  become: yes
  dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
    disable_gpg_check: yes
  tags: ['rpm_fusion']
  when: enable_free_rpm_fusion

- name: Enable the Non-Free RPM Fusion repository
  become: yes
  dnf:
    name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
    disable_gpg_check: yes
  tags: ['rpm_fusion']
  when: enable_nonfree_rpm_fusion
