---
- name: Ensure 1password repository is added
  include_tasks: "add_repo/{{ ansible_os_family }}.yml"

- name: Ensure 1password is present
  become: yes
  package:
    name: ["1password", "1password-cli"]
    state: present
